(DataBaseTableListing): Create a Product Listing Model
toursbylocals/tblv3-api pull request #26
Opened 2022-07-20 21:40 UTC by growebux

Acs:

- [x]  Create a Schema/Models for Product Listing
- [x]  Create a Schema/Models for Product Type
- [x]  Run Test

2022-07-23 03:24 UTC, codedavinci requested changes

2022-07-23 03:24 UTC, codedavinci commented on src/models/listing.ts
> +      default: () => Date.now()
Every location should have a startTime date with hours.

2022-07-25 16:25 UTC, growebux commented
We are working on the modifications.

Thanks

2022-07-25 16:59 UTC, growebux commented
@Eddie
 Could you review the modification Jenny and I did?

We are going to add the attributes to the model.

One hour to finish it.

@DongJoSuh @jeannejx @codedavinci

2022-07-26 18:26 UTC, merged