[WIP] feat(listingSearchApi): create resolvers for listing search api
toursbylocals/tblv3-api pull request #31
Opened 2022-07-27 15:38 UTC by DongJoSuh

2022-07-28 16:47 UTC, codedavinci requested changes

2022-07-28 16:47 UTC, codedavinci commented on src/resolvers/index.ts
> +    listingsFilterByProductType: async (_, __, { filter }) => {
These filters will have to be all in one. The name of the resolver will be only `listings`

2022-07-28 16:47 UTC, codedavinci commented on src/resolvers/index.ts
> +    listingsFilterByProductType: async (_, __, {}) => {
It's meant to be one resolver for this: `listing`

2022-07-28 16:47 UTC, codedavinci commented on src/resolvers/listing.ts
> +export const getListingsFilterByTitle = async (filter: string) => {
as I said yesterday these methods can be bound to the model and the filters must be passed as arguments.

2022-07-28 16:47 UTC, codedavinci commented on src/schemas/entities.ts
> +    listingsFilterByProductType(filter: String): [Listing]!
`listings(filter: filterInput): [Listing]`

2022-07-28 22:35 UTC, codedavinci commented on src/resolvers/index.ts
> +      return await getListings(FilterInput)
`await Listing.getListings(FilterInput)`

2022-07-29 19:15 UTC, codedavinci approved these changes

2022-07-29 19:15 UTC, codedavinci commented on src/schemas/entities.ts
> +    trait: [String]
Add `keywords`

2022-08-03 19:20 UTC, DongJoSuh commented
there is a block; i need calendar model to filter listing by date. going to pause on this ticket and work on ticket#36 - model Calendar

2022-09-01 23:46 UTC, closed without merging